# Generated by Django 6.0.3 on 2026-03-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fellowship", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UndergraduateApplication",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=255)),
                ("degree_program", models.CharField(max_length=255)),
                ("year_of_study", models.CharField(max_length=50)),
                ("gpa", models.CharField(max_length=10)),
                ("availability", models.CharField(max_length=100)),
                ("time_zone", models.CharField(max_length=50)),
                ("target_lab_first", models.CharField(max_length=100)),
                (
                    "target_lab_second",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("portfolio_link", models.URLField(blank=True, null=True)),
                ("cv", models.FileField(upload_to="undergraduate/cv/")),
                (
                    "transcript",
                    models.FileField(upload_to="undergraduate/transcripts/"),
                ),
                ("statement", models.FileField(upload_to="undergraduate/statements/")),
                (
                    "sample_work",
                    models.FileField(
                        blank=True, null=True, upload_to="undergraduate/samples/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
