# Generated by Django 6.0.3 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fellowship", "0003_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Fellow", "Fellow"),
                            ("Mentor", "Mentor"),
                            ("Researcher", "Researcher"),
                            ("Partner", "Partner"),
                            ("Subscriber", "Subscriber"),
                        ],
                        default="Subscriber",
                        max_length=50,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
